---
title: "Resources"
---

# Resources for Orthoptera ID 

This page is a collection of resources that will be used throughout the duration of this project. They will all come in handy. The best workflow will start with the first two resources listed and then continue to compare the resources together to make an informed decision.

### 1. [Orthoptera Song Guide](https://docs.google.com/spreadsheets/d/1klMWGWtpvWHylVUaaB9nnBOiFvXm6wb4ZrrdUU_eoO0/edit?usp=sharing)

This guide details all the possible species that occur in our sampling region along with their frequency range, signal morphology, and links to example recordings. This guide should be used every time an Orthopteran is identified in this project.

### 2. [Singing Insects of North America (SINA)](https://orthsoc.org/sina/)

SINA is the main resource used in the Orthoptera Song Guide. It will have examples and/or information for all the species in the sampling region. Other resources might not have a full record, but for some species other resources might provide valuable alternative examples to SINA and/or necessary information to make a proper ID.

### 3. [Song of Insects](https://docs.google.com/spreadsheets/d/1klMWGWtpvWHylVUaaB9nnBOiFvXm6wb4ZrrdUU_eoO0/edit?usp=sharing) 

Song of Insects is an online database with the most common species. This database often has acoustic-specific information which SINA sometimes does not, as well as more examples of song patterns—sometimes recorded in the field. This can be useful to compare the variation between different resources and our field recordings.

### 4. [Xeno Canto](https://xeno-canto.org/)

Xeno Canto is the best resource for field recordings but might not have all the species in the sampling region. Also, since Xeno Canto is a community science database the recording examples will be biased towards popular and common species.

# Project-specific tips and tricks
